### ISSUE TITLE
Compatibility with PDI 8.1 (WebSpoon)

### ISSUE THREAD

**Issue by PovilasKud** [atolcd/pentaho-gis-plugins#19]
Trying to make it work with PDI 8.1 (on webspoon)

The first error I get is:
`java.lang.NoClassDefFoundError: org/apache/commons/vfs/FileSystemException`

This is fixed by adding commons-vfs-1.0.jar, but following error appears:
 `java.lang.NoSuchMethodError: org.pentaho.di.core.vfs.KettleVFS.getFileObject(Ljava/lang/String;)Lorg/apache/commons/vfs/FileObject;`

Any suggestions what could be done to make this work ?
